console.log(20 + 10);
console.log("Hello World");
let x = "abebe beso bela";
console.log(x);
const y = "Alemu tebela";
console.log(y);
var num1 = 15;
var num2 = 20;
var sum = num1 + num2;
var pro = num1 * num2;
console.log(sum);
console.log(pro);
console.log(5 != 5);
console.log(5 == 5);
console.log(5 === "5");
console.log(4 == 5 || 5 == 4);
console.log(5 == 5 && 6 != 5);
var myFirstArray = [1800, "Abebe", "Alemu", 300];
console.log(myFirstArray);
console.log(myFirstArray[0] + myFirstArray[3]);
myFirstArray[1] = "Abebech";
console.log(myFirstArray);
